In [1]:
import pandas as pd
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sentences = [
    'The glass of milk',
    'The glass of juice',
    'The cup of tea',
    'I am a good boy',
    'I am a good developer',
    'Understand the meaning of words',
    'Your videos are good'
]

In [3]:
sentences

['The glass of milk',
 'The glass of juice',
 'The cup of tea',
 'I am a good boy',
 'I am a good developer',
 'Understand the meaning of words',
 'Your videos are good']

In [4]:
## Define the vocabulary size
voc_size = 10000

In [5]:
## one hot 
one_hot_rep = [one_hot(words,voc_size) for words in sentences]
one_hot_rep


[[4009, 5959, 4461, 2087],
 [4009, 5959, 4461, 5020],
 [4009, 3032, 4461, 8796],
 [7433, 1824, 1317, 705, 1768],
 [7433, 1824, 1317, 705, 1856],
 [5947, 4009, 9064, 4461, 6654],
 [5851, 777, 8043, 705]]

In [6]:
### Word embedding repres

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)

In [ ]:
embedded_docs    ### Sentence become of equal length

array([[   0,    0,    0,    0, 4009, 5959, 4461, 2087],
       [   0,    0,    0,    0, 4009, 5959, 4461, 5020],
       [   0,    0,    0,    0, 4009, 3032, 4461, 8796],
       [   0,    0,    0, 7433, 1824, 1317,  705, 1768],
       [   0,    0,    0, 7433, 1824, 1317,  705, 1856],
       [   0,    0,    0, 5947, 4009, 9064, 4461, 6654],
       [   0,    0,    0,    0, 5851,  777, 8043,  705]])

In [10]:
### Feature Representation
dim = 10

In [11]:
model  = Sequential()
model.add(Embedding(voc_size,dim,input_length = sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 293ms/step


array([[[ 0.01075971,  0.0272194 , -0.02345293,  0.02723645,
          0.03216637,  0.01258017,  0.04928037, -0.00314806,
          0.00629755, -0.00551005],
        [ 0.01075971,  0.0272194 , -0.02345293,  0.02723645,
          0.03216637,  0.01258017,  0.04928037, -0.00314806,
          0.00629755, -0.00551005],
        [ 0.01075971,  0.0272194 , -0.02345293,  0.02723645,
          0.03216637,  0.01258017,  0.04928037, -0.00314806,
          0.00629755, -0.00551005],
        [ 0.01075971,  0.0272194 , -0.02345293,  0.02723645,
          0.03216637,  0.01258017,  0.04928037, -0.00314806,
          0.00629755, -0.00551005],
        [ 0.0061623 , -0.02654036, -0.01262505, -0.00532036,
         -0.04169006,  0.02876247,  0.01198865,  0.0078088 ,
         -0.0050711 ,  0.01037287],
        [-0.02902657,  0.01691077,  0.04015069, -0.03757102,
          0.04219439,  0.01873172,  0.0078495 , -0.03070196,
         -0.02412125,  0.01457461],
        [-0.04584837, -0.00483435, -0.01336942,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 4009, 5959, 4461, 2087])